import './globals.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Preahvihear } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const preahvihear = Preahvihear({
  weight: '400', // only one weight exists for this font
  subsets: ['latin'],
  variable: '--font-preahvihear',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${preahvihear.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

